// Package sandbox manages the embedded bwrap binary used for tool isolation.
//
// The bwrap binaries are generated by running:
//
//	go generate ./sandbox/...
//
// which invokes scripts/fetch_bwrap.go to build static bubblewrap binaries
// for each supported architecture. The resulting binaries are gitignored;
// re-run go generate after a clean clone.
package sandbox

import (
	"embed"
	"fmt"
	"os"
	"runtime"
)

//go:generate go run ../scripts/fetch_bwrap.go

// binFS holds the bwrap binary for each supported OS/arch combination.
// Files are populated by go generate; the directories always contain at least
// a version.txt so the embed directive compiles on a clean clone.
//
//go:embed linux_amd64 linux_arm64
var binFS embed.FS

// BwrapVersion is the pinned bubblewrap release embedded in this build.
const BwrapVersion = "v0.11.0"

// Extract writes the bwrap binary for the current OS/arch to a new temporary
// file, marks it executable (0700), and returns the path.
//
// The caller is responsible for removing the file when it is no longer needed
// (typically at agent shutdown). Returns an error if the binary for this
// architecture was not embedded (go generate was not run for this arch).
func Extract() (string, error) {
	key := fmt.Sprintf("%s_%s/bwrap", runtime.GOOS, runtime.GOARCH)
	data, err := binFS.ReadFile(key)
	if err != nil {
		return "", fmt.Errorf("sandbox binary not available for %s/%s (run: go generate ./sandbox/...): %w",
			runtime.GOOS, runtime.GOARCH, err)
	}
	if len(data) == 0 {
		return "", fmt.Errorf("sandbox binary for %s/%s is empty (did go generate complete successfully?)",
			runtime.GOOS, runtime.GOARCH)
	}

	f, err := os.CreateTemp("", "bwrap-*")
	if err != nil {
		return "", fmt.Errorf("creating temp file for sandbox binary: %w", err)
	}

	path := f.Name()
	if _, err := f.Write(data); err != nil {
		f.Close()
		os.Remove(path)
		return "", fmt.Errorf("writing sandbox binary: %w", err)
	}
	if err := f.Chmod(0700); err != nil {
		f.Close()
		os.Remove(path)
		return "", fmt.Errorf("marking sandbox binary executable: %w", err)
	}
	f.Close()

	return path, nil
}
